{
  "lang": "en",
  "title": "Lv105 Farming Sheet F105 - DFCAT",
  "common": {
    "option": " Option",
    "damage": "Damage",
    "buff": "Buff",
    "availableLevel": "Available Level",
    "status": "Status",
    "buffOption": "Buffer Only"
  },
  "main": {
    "guide": {
      "warning": "DFCAT F105 is more easier after read the guide",
      "ask": "Would you read the guide?",
      "nomore": "never",
      "agree": "Yes",
      "disagree": "No"
    }
  },
  "preset": {
    "title": "Preset",
    "loaded": "loaded",
    "delete": "Delete",
    "deleted": " is deleted",
    "save": "Save",
    "saved": "Saved",
    "create": "Create New Preset",
    "deleteConfirm": "Deleted preset cannot be recovered. Are you sure?",
    "empty": "Empty presets.",
    "emptyGuide": "You can save current state into preset by characters or settings.",
    "adblock": "Under ADBLOCK, you can use presets upto 5"
  },
  "set": {
    "placeholder": "Partial Search by ItemName (ex: ay dr -> 'dr'agon sl'ay'er)",
    "releaseAllItems": "releaseAllItems",
    "hideAll": "hideAll",
    "showAll": "showAll",
    "showWannabeOnly": "showWannabeOnly",
    "showAllSets": "showAllSets",
    "labelObjection": "Better composition than proposed settings can be. You with objection are correct.",
    "labelExclude": "Good item under some condition only (capital, melee, etc) are excluded.",
    "labelCustomizing": "Customize items for your condition.",
    "reference": "Reference",
    "setNameBefore": "",
    "setNameAfter": "created set item names, not official."
  },
  "item": {
    "growInfo": "Grow Info",
    "totalDamage": "Total Damage",
    "totalBuff": "Total Buff"
  },
  "dungeon": {
    "labelNamedSelectedItems": "Named monsters which selected items drop",
    "labelNamedDesc": "By click named's name, show items droped by that named",
    "labelItems": "Items can obtain in this dungeon",
    "labelMonsterCount": "Will be updated",
    "drops": " drops",
    "modeRoad": "Road",
    "modeBoss": "Boss",
    "modeNamed": "All Named",
    "modeMonster": "Monster Count",
    "modeSelected": "Selected Named",
    "labelExtension1": "Map of Extended Dungeon",
    "labelExtension2": "is not supported",
    "labelExtension3": "in F105"
  },
  "dungeons": {
    "normal": "Normal",
    "extension": "Extension",
    "all": "All"
  },

  "상의": "Jacket",
  "하의": "Pants",
  "머리어깨": "Shoulder",
  "허리": "Waist",
  "신발": "Shoes",
  "팔찌": "Wrist",
  "목걸이": "Necklace",
  "반지": "Ring",
  "보조장비": "Support",
  "마법석": "Magic Stone",
  "귀걸이": "Earring",
  "아칸 코어픽": "Archon Core",
  "아칸 추천셋": "Archon Optimal",
  "아칸 대체픽": "Archon Alter",
  "과소모 코어픽": "Overuse Core",
  "과소모 추천셋": "Overuse Optimal",
  "과소모 대체픽": "Overuse Alter",
  "기본기 코어픽": "Basic Core",
  "기본기 추천셋": "Basic Optimal",
  "기본기 대체픽": "Basic Alter",
  "화상 코어픽": "Burn Core",
  "화상 추천셋": "Burn Optimal",
  "화상 대체픽": "Burn Alter",
  "감전 코어픽": "Elec. Shock Core",
  "감전 추천셋": "Elec. Shock Optimal",
  "감전 대체픽": "Elec. Shock Alter",
  "출혈 코어픽": "Bleeding Core",
  "출혈 추천셋": "Bleeding Optimal",
  "출혈 대체픽": "Bleeding Alter",
  "중독 코어픽": "Poison Core",
  "중독 추천셋": "Poison Optimal",
  "중독 대체픽": "Poison Alter",
  "자본픽": "Capital",
  "근접픽": "Melee",
  "노블레스 코드 날먹": "Riding(For Nobless Code)",

  "데저트 베테랑 솔저": "Desert Beteran Soldier",
  "팬텀 노블레스": "Phantom Nobless",
  "어둠의 방랑자": "Dark Wanderer",
  "탐사와 모험의 고고학자": "Archaeologist",
  "논 아크로매틱": "Non Archromatic",
  "끝없이 이어지는 꿈의 울림": "Everlasting Ring of Dream",
  "라이트 라이프 에코": "Light Life Echo",
  "고대 수호자의 잔해": "Remnant of Ancient Guardian",
  "어우러지는 자연의 정수": "Mingled Essense of Nature",
  "윙 피스메이커": "Wing Peacemaker",
  "오퍼레이션 A": "Operation A.W.",
  "오퍼레이션 A.W.": "Operation A.W.",
  "바래어진 헤블론의 유산": "Faded Lagacy of Heblon",
  "사라져가는 이성의 잔재": "Dregs of Vanishing Sanity",
  "드레드 오브 드래곤": "Dread of Dragon",
  "프라이스 오브 리버티": "Price of Liberty",
  "오버 디케이드 테크놀로지": "Over Decade Technology",
  "워프 디스토션": "Warp Distortion",
  "물들지 않는 의지의 고결함": "Nobility of the Untainted Will",
  "헌티드 레어 아티팩트": "Haunted Rare Artifect",
  "매드 사이언티스트 지젤": "Mad Scientist Gizel",
  "이스핀즈": 'Ispins',
  "숲속의 마녀": "Witch in the Woods",
  "엔트 정령": "Treant Spirit",
  "블루 베릴": "Blue Beryl",
  "딥 다이버": "Deep Diver",

  "아머드 파워 상의": "Armored Power Top",
  "플래티넘 클래스 재킷": "Platinum Class Jacket",
  "죽음에 잠식된 갑주": "Armor Engulfed By Death",
  "탐험가의 노련한 코트": "Explorer'S Seasoned Coat",
  "쉐도우블랙 슈트": "Shadow Black Coat",
  "어릴적 꿈꿔온 무대": "The Stage I Dreamed Of As A Child",
  "리버시블 레더 코트": "Reversible Leather Coat",
  "천지를 흔드는 석갑": "Stone Gloves That Shake The Sky",
  "흙으로 빚은 자연": "Nature Made Of Soil",
  "천상을 수호하는 윙 아머": "Wing Armor To Protect The Heavens",
  "하이테크 전술지휘 아머": "High-Tech Tactical Command Armor",
  "미련이 남은 녹슨 원혼": "Rusty Ghosts Left Behind",
  "천재 기술자의 전문 작업복 상의": "Genius Technician'S Professional Work Wear Top",
  "격동하는 마음": "Pounding Heart",
  "드래곤 슬레이어": "Dragon Slayer",
  "얼티밋 제너레이터": "Ultimate Generator",
  "어비스 리액터": "Abyss Reactor",
  "고귀한 신의": "Noble God",
  "옥화의 망령 흉갑": "Jade's Wraith Breastplate",
  "혼돈을 두른 장막": "Veil Of Chaos",
  "데저트 테크놀로지 팬츠": "Desert Technology Trousers",
  "네오 화이트 클래스 팬츠": "Neo White Class Pants",
  "지치지 않는 여정의 하의": "Bottoms Of A Tireless Journey",
  "라이트 어댑터 팬츠": "Light Adapter Pants",
  "무대의 화려함": "The Splendor Of The Stage",
  "벤타블랙 팬츠": "Venta Black Pants",
  "숨쉬는 자연의 생명": "Breathing Nature Life",
  "평화를 수호하는 윙 레깅스": "Wing Leggings To Keep The Peace",
  "압도하는 힘의 하갑": "Armor Of Overwhelming Power",
  "깨지지 않는 빛바랜 신념": "Unbreakable, Faded Beliefs",
  "하이테크 전술보조 각반": "High-Tech Tactical Assistant Gaiters",
  "드래곤 라이더": "Dragon Rider",
  "침식되는 이성": "Erosion Of Reason",
  "천재 기술자의 멀티박스 팬츠": "Genius Technician'S Multibox Pants",
  "굳건한 믿음": "Strong Faith",
  "스톰라이더": "Storm Rider",
  "옥화의 망령 대퇴갑": "Wraith Of Jade Gauntlets",
  "언리밋 사이버네틱": "Unlimited Cybernetic",
  "끝을 바라보는 시선": "Gaze Towards The End",
  "자신감의 백색 망토": "White Cloak Of Confidence",
  "데저트 컨실멘트 숄더": "Desert Concealment Shoulder",
  "근력 보강 숄더": "Muscle Reinforcement Shoulder",
  "블랙 캣 헬멧": "Black Cat Helmet",
  "화려한 청색의 음율": "Colorful Blue Tones",
  "마그네틱 서치 스캔": "Magnetic Search Scan",
  "자유를 수호하는 윙 숄더": "Wing Shoulder To Protect Freedom",
  "피어나는 자연의 삶": "Blooming Natural Life",
  "오염된 빙석 견갑": "Corrupted Icestone Pauldrons",
  "주체할 수 없는 낡은 규칙": "Old Rules That Can'T Be Controlled",
  "하이테크 바디 프로텍트 숄더": "High-Tech Body Protect Shoulder",
  "드래곤 헌터": "Dragon Hunter",
  "빛을 잃은 진실": "The Lost Truth",
  "천재 기술자의 보호 마스크": "Genius Engineer'S Protective Mask",
  "맹렬한 위세": "Fierce Dominance",
  "옥화의 망령 상박갑": "Jade Flower'S Specter Bracers",
  "헥타곤 임펄스 브릭": "Hectagon Impulse Brick",
  "매니퓰레이션": "Manipulation",
  "옭아매는 공포": "Suffocating Fear",
  "익스펜션 서플라이 벨트": "Expansion Supply Belt",
  "고고함의 백색 벨트": "White Belt Of Nobility",
  "썬더 레지스트 벨트": "Thunder Resist Belt",
  "가이드 라인 벨트": "Guide Line Belt",
  "별을 담는 벨트": "Belt With Stars",
  "음율에 담은 소망": "Hope In The Melody",
  "불변의 부유석 벨트": "Immutable Floating Stone Belt",
  "하이테크 서플라이 벨트": "Hi-Tech Supply Belt",
  "순수한 자연의 이치": "Pure Nature",
  "마주할 수 없는 부러진 긍지": "Broken Pride That Cannot Be Faced",
  "대지를 수호하는 윙 벨트": "The Wing Belt That Protects The Earth",
  "파괴된 신념": "Destroyed Beliefs",
  "천재 기술자의 멀티툴 벨트": "Genius Engineer'S Multi-Tool Belt",
  "드래곤 스케빈저": "Dragon Scavenger",
  "얼터레이션 다이얼 벨트": "Alternating Dial Belt",
  "마땅한 본분": "Proper Duty",
  "옥화의 망령 요갑": "Jade Flower'S Specter Gauntlets",
  "파워 플랜트": "Power Plant",
  "신비함의 백색 구두": "Mystery White Shoes",
  "HEM 리인포스 부츠": "Hem Line Force Boots",
  "절망의 발소리": "Footsteps Of Despair",
  "일렉트릭 프루프 부츠": "Electric Proof Boots",
  "검은 발자국": "Black Footprints",
  "대지를 딛는 부츠": "Boots On The Ground",
  "소망을 전하는 편지": "A Letter Of Hope",
  "순환하는 자연의 섭리": "Cycle Of Nature",
  "어둠에 삼켜진 돌굽": "Stonehoof Swallowed By Darkness",
  "하이테크 고기동 강화 부츠": "High-Tech High Mobility Reinforced Boots",
  "움직이는 쇠약한 집착": "Moving Debilitating Obsession",
  "하늘을 수호하는 윙 부츠": "Wing Boots To Protect The Sky",
  "폭주하는 육신": "A Raging Body",
  "드래곤 패스파인더": "Dragon Pathfinder",
  "천재 기술자의 두터운 보호부츠": "Genius Engineer'S Thick Protective Boots",
  "내딛는 용기": "Courage To Step",
  "엑셀러레이터": "Accelerator",
  "스팀펑크 소닉 디스럽터": "Steampunk Sonic Disruptor",
  "옥화의 망령 각갑": "Jade Wraith Greaves",
  "기사의 구원": "Knight'S Salvation",
  "억제된 마력의 팔찌": "Bracelet Of Suppressed Magic",
  "아크 블라스터 소스": "Arc Blaster Sauce",
  "전술 드론 콘트롤러 암릿": "Tactical Drone Controller Armlet",
  "생명이 담긴 가죽 토시": "Lifelike Leather Tosi",
  "화음하는 음색": "Harmonious Tone",
  "세컨드 스페이드 - 어쏘러티": "Second Spade - Authority",
  "리플레이서": "Replayer",
  "미니어쳐 헤드셋 암릿": "Miniature Headset Armlet",
  "작은 풀잎의 순수함": "The Innocence Of A Small Blade Of Grass",
  "흑화의 구속 팔찌": "Black Flower'S Restraint Bracelet",
  "구속된 자유": "Bound Freedom",
  "찬란한 금장 팔찌": "Brilliant Gold Bracelet",
  "수호룡의 비호 - 자비": "Guardian Dragon'S Protection - Mercy",
  "포인트 레이더 암릿": "Point Radar Armlet",
  "골렘의 핵 팔찌": "Golem's Nuclear Bracelet",
  "무뎌지는 둔화된 변화": "Blunt, Sluggish Change",
  "이온화조정 팔찌": "Ionization Control Bracelet",
  "수확하는 옥수": "Harvesting Corn",
  "냉혹한 현실의 목걸이": "Necklace Of Harsh Reality",
  "고양된 분노의 목걸이": "Necklace Of Exalted Fury",
  "골렘의 심장 목걸이": "Golem'S Heart Necklace",
  "임펄스 트리거": "Impulse Trigger",
  "수호룡의 비호 - 용기": "Guardian Dragon'S Protection - Courage",
  "기품의 금빛 장신구": "Elegant Gold Ornaments",
  "절대감각의 방위구": "Absolute Sense Of Defense",
  "테크놀로지 바디캠 네클리스": "Techology Body Cam Necklace",
  "솔저 호너 네클리스": "Soldier Horner Necklace",
  "잠겨진 영역": "Locked Area",
  "죄어오는 풍화된 악의": "Sinking Weathered Malice",
  "검은 별": "Black Star",
  "약동하는 생명의 고동": "Vibrating Beat Of Life",
  "퍼스트 스페이드 - 노블레스": "First Spade - Noblesse",
  "푸른 자연의 씨앗": "Blue Nature Seeds",
  "머신 컨트롤러 리모트": "Machine Controller Remote",
  "기사의 속죄": "Knight'S Atonement",
  "잔잔한 선율": "Gentle Melody",
  "디젯 퓨즈 초크": "Djet Fuse Choke",
  "개화하는 신비의 꽃": "Mysterious Flower Blooming",
  "자기장 탐지링": "Magnetic Field Detection",
  "오버커런트 마그넷 링": "Overcurrent Magnet Ring",
  "골드 윙 반지": "Gold Wing Ring",
  "반짝이는 음율": "Sparkling Cry",
  "고통의 상처": "Pain Of Pain",
  "핏빛의 결정 반지": "Blood Crystal Ring",
  "빛을 발하는 생명": "Life That Shines",
  "기사의 긍지": "Knight'S Pride",
  "원터치 스마트 리모콘": "One-Touch Smart Remote Control",
  "골렘의 중추석 반지": "Golem'S Keystone Ring",
  "레드 라이프 링": "Red Life Ring",
  "뚜렷해지는 소멸된 사념": "Disappeared Thoughts Becoming Clear",
  "서드 스페이드 - 데스": "Third Spade - Death",
  "수호룡의 비호 - 축복": "Guardian Dragon'S Protection - Blessing",
  "멈추지 않는 운명": "Unstoppable Fate",
  "이동하는 요새": "Moving Fortress",
  "전술 레이더망 링": "Tactical Radar Mesh",
  "어댑터블 투톤 링": "Adaptable Two-Tone Ring",
  "생명의 근원이 담긴 배낭": "A Backpack Containing The Source Of Life",
  "터치 컨트롤 패널": "Touch Control Panel",
  "드러나는 흐릿한 지식": "Blurry Knowledge Revealed",
  "여명의 성배": "Chalice Of The Dawn",
  "굴착 강화 파츠": "Excavation Reinforcement Parts",
  "죽음을 부르는 관": "Coffin Of Death",
  "불길한 데칼코마니 석판": "Ominous Decalcomani Slab",
  "미지의 문명 - 마스크 스톤": "Unknown Civilization - Mask Stone",
  "내면의 얼굴": "Inner Face",
  "정의의 기사 가면": "Knight Of Justice Mask",
  "버츄얼 사이트 글래스": "Virtual Sight Glass",
  "파괴된 생명": "Destroyed Life",
  "꿈같은 환호성": "Dream-Like Cheers",
  "올 오어 원 매직박스": "All Or One Magic Box",
  "용살자의 증표 - 용골 뿔피리": "Token Of The Dragon Slayer - Keel Horn",
  "찰랑이는 생명수": "Sparkling Water Of Life",
  "데카 가이던스 디바이스": "Deca Guidance Device",
  "공중형 : 전술 프롭 드론": "Aerial: Tactical Prop Drone",
  "홀로그램 콜": "Hologram Call",
  "자연에 녹아드는 이슬": "Dew That Melts In Nature",
  "선회하는 흐려진 혜안": "Clouded Shores Turning",
  "잿빛의 묘상석": "Gray Gravestone",
  "지상형 : 전술 차륜 드론": "Ground Type: Tactical Wheeled Drone",
  "용살자의 증표 - 용심 가공석": "Token Of The Dragon Slayer - Dragon Heart Processing Stone",
  "저주받은 마음": "Cursed Heart",
  "도데카 홀로그램": "Dodeca Hologram",
  "생명이 깃든 초록빛 액체": "Green Liquid Of Life",
  "미지의 문명 - 스타 스톤": "Unknown Civilization - Star Stone",
  "피어오르는 광기": "Blaze Of Madness",
  "미니 배터리 팩": "Mini Battery Pack",
  "언비튼 메달": "Unbeaten Medal",
  "어둠을 먹는 심장": "Heart That Eats Darkness",
  "거짓 속의 거짓": "Lies In Lies",
  "두근거리는 열정": "Pounding Passion",
  "억류된 혼의 령주": "Command Master Of The Imprisoned Soul",
  "평화를 위한 투쟁": "Struggle For Peace",
  "미지의 황금비석": "Unknown Golden Stone",
  "자정의 성역": "Midnight Sanctuary",
  "미지의 문명 - 트윈 스톤": "Unknown Civilization - Twin Stones",
  "폭풍을 삼킨 에너지": "Energy That Swallowed The Storm",
  "생명을 키우는 코발트 스틱": "A Cobalt Stick That Nourishes Life",
  "부스팅 펄스 튜브": "Boosting Pulse Tube",
  "인력의 법칙": "Law Of Gravity",
  "용살자의 증표 - 용린 귀걸이": "Token Of The Dragon Slayer - Dragon Earrings",
  "저주받은 굴레": "Cursed Bridle",
  "오퍼레이션 오더": "Operation Order",
  "타락한 영혼": "Fallen Soul",
  "아크로매틱 룸버스": "Achromatic Roombus",
  "들이치는 희미한 탄식": "Faint Sighs",
  "폭발형 : 소형 전술 플레어": "Explosive: Small Tactical Flare",
  "청명한 아침의 새싹": "Buds Of Clear Morning",
  "시각의 관점": "Point Of View",
  "마음을 전달하는 소리": "Sound That Conveys The Heart",
  "엔데카 코어 칩": "Endeca Core Chip",
  "배회하는 혼령의 향로": "Censer Of Wandering Spirits",
  "황혼의 성단": "Twilight Star Cluster",
  "하늘에 휘날리는 깃털": "Feathers Flying In The Sky",
  "숲속의 마녀 상의": "Forest Witch Jacket",
  "숲속의 마녀 하의": "Forest Witch Pants",
  "숲속의 마녀 망토": "Forest Witch Cloak",
  "숲속의 마녀 벨트": "Forest Witch Belt",
  "숲속의 마녀 신발": "Forest Witch Shoes",
  "숲속의 마녀 팔찌": "Forest Witch Bracelet",
  "숲속의 마녀 목걸이": "Forest Witch Necklace",
  "숲속의 마녀 반지": "Forest Witch Ring",
  "숲속의 마녀 바구니": "Forest Witch Basket",
  "숲속의 마녀 정령석": "Forest Witch Spirit Stone",
  "숲속의 마녀 귀걸이": "Forest Witch Earrings",
  "엔트 정령의 상의": "Treant Spirit'S Top",
  "엔트 정령의 하의": "Treant Spirit'S Pants",
  "엔트 정령의 어깨": "Treant'S Shoulder",
  "엔트 정령의 벨트": "Ent Spirit Belt",
  "엔트 정령의 신발": "Treant Spirit'S Shoes",
  "엔트 정령의 팔찌": "Treant Spirit'S Bracelet",
  "엔트 정령의 목걸이": "Treant Spirit'S Necklace",
  "엔트 정령의 반지": "Treant Spirit'S Ring",
  "엔트 정령의 성배": "Treant Spirit'S Grail",
  "엔트 정령의 심장": "Treant Spirit'S Heart",
  "엔트 정령의 귀걸이": "Treant Spirit'S Earrings",
  "블루 베릴 아머": "Blue Beryl Armor",
  "블루 베릴 하의": "Blue Beryl Bottoms",
  "블루 베릴 보호대": "Blue Beryl Protector",
  "블루 베릴 벨트": "Blue Beryl Belt",
  "블루 베릴 부츠": "Blue Beryl Boots",
  "블루 베릴 암릿": "Blue Beryl Armlet",
  "블루 베릴 네클레스": "Blue Beryl Necklace",
  "블루 베릴 링": "Blue Beryl Ring",
  "블루 베릴 퍼퓸": "Blue Beryl Perfume",
  "블루 베릴 젬스톤": "Blue Beryl Gemstone",
  "블루 베릴 이어링": "Blue Beryl Earrings",
  "대제사장의 예복": "Arch Celebrant's Gown",
  "대 마법사 [???]의 로브": "Archmage [???]'s Robe",
  "낭만적인 선율의 왈츠": "Romantic Waltz",
  "고대 심연의 로브": "Ancient Abyssal Robe",
  "생사를 다스리는 그림자의 재킷": "Shadowy Fate Governor Jacket",
  "수석 집행관의 코트": "Senior Executor's Coat",
  "최후의 전술": "Last-ditch Effort",
  "길 방랑자의 물소 코트": "Drifter's Water Buffalo Coat",
  "작열하는 대지의 용맹": "Blazing Valor of Earth",
  "트로피카 : 드레이크": "Tropica: Drake",
  "웨어러블 아크 팩": "Wearable Arc Pack",
  "종말의 역전": "Reversed End",
  "사탄 : 분노의 군주": "Satan: The Furious Monarch",
  "천상의 날개": "Heavenly Wings",
  "결속의 체인 플레이트": "Solidarity Chain Plate",
  "세상을 삼키는 분노": "Apocalyptic Fury",
  "선택이익": "Selective Advantage",
  "영명한 세상의 순환": "Mystical Circulation of the World",
  "원시 태동의 대지": "Land of the Primordial Beginning",
  "라이도 : 질서의 창조자": "Raido: The Creator of Order",
  "새벽을 녹이는 따스함": "Dawning Glow",
  "가네샤의 영원한 가호": "Ganesha's Everlasting Blessing",
  "지고의 화염 - 이프리트": "Supreme Flame: Ifrit",
  "영원히 끝나지 않는 탐구": "Endless Research",
  "시간을 거스르는 자침": "Time-defying Magnetic Needle",
  "천지에 울려퍼지는 포효": "Sonorous Battle Roar",
  "숙명을 뒤엎는 광란": "Fate Rampager",
  "군신의 마지막 갈망": "War God's Last Desire",
  "영원을 새긴 바다": "Sea of Eternal Promises",
  "또다른 시간의 흐름": "Another Flow of Time",
  "플라즈마 초 진공관": "Plasma Super Vacuum Tube",
  "영원한 나락의 다크버스": "Eternally Abyssal Darkverse",
  "차원을 관통하는 초신성": "Interdimensional Supernova",
  "운명을 거스르는 자": "Destiny Defier",
  "아린 고통의 비극": "Excruciating Tragedy",

  "백색의 땅": "White Land",
  "베리콜리스": "Vericollis Temple",
  "캐니언 힐": "Canyon Hill",
  "퀸 팔트": "Queen Palt",
  "왕의 요람": "King's Cradle",
  "헤블론의 예언소": "Heblon's Prophecy",
  "나사우 삼림": "Nasau Forest",
  "이터널 플레임 연구소": "Eternal Flame Lab",
  "노블레스 코드": "Nobless Code",
  "파괴된 죽은 자의 성(상급)": "Destroyed Castle of the Dead",

  "혼돈의 천사 루치펠": "Luciferre, the Angel of Chaos",
  "스페시오": "Specio",
  "순결한 파이디온": "A Pure Paidion",
  "빛의 괴수 피톤": "Monster of Light, Python",
  "성전의 영령": "Heroic Spirit of the Temple",
  "성화의 라미에르": "Lamière of the torch",
  "대천사 미카엘": "Archangel Michael",
  "속사 루이스 / 쾌검 폴센": "Louis / Poulsen",
  "그림자 모슬리": "Shadow Mosley",
  "볼트 MX3": "Volt MX3",
  "제국 투사 바스커빌": "Imperial Fighter Baskerville",
  "요원 707": "Agent 707",
  "강철의 비비안": "Fullmetal Bibiane",
  "매드 리케": "Mad Rike",
  "루퍼트 도스타": "Rupert Dostar",
  "킹 디스트로이어": "King Destroyer",
  "퀸 디스트로이어": "Queen Destroyer",
  "말괄량이 베키": "Tomboy Becky",
  "베키의 잃어버린 가방": "Lost Bag of Becky",
  "되살아난 골드 크라운": "Revived Gold Clown",
  "어둠의 골고타": "Dark Golgotha",
  "빛의 칼바리": "Calbary of Light",
  "심연을 걷는 자": "Abyss Walker",
  "드락카니다": "Drakkanida",
  "드락카 앙스트": "Drakka Anst",
  "드락카 앙스트 zero": "Drakka Anst zero",
  "대장 스타크": "Captain Stark",

  "구매 가능": "Shop",
  "네임드": "Named",
  "공격 속도": "Attack Speed",
  "캐스팅 속도": "Casting Speed",
  "크리티컬 히트": "Critical Hit",
  "피해 증가": "Damage",
  "HP 회복": "HP 회복",
  "이동 속도": "Move Speed",
  "방어력": "방어력",
  "HP MAX": "HP MAX",
  "스킬 공격력 증가": "스킬 공격력 증가",
  "MP 회복": "MP 회복",
  "적중률": "적중률",
  "화속성 강화": "화속성 강화",
  "구매 불가": "구매 불가",
  "커스텀": "Custom",
  "명속성 강화": "명속성 강화",
  "수속성 강화": "수속성 강화",
  "스킬 쿨타임": "스킬 쿨타임",
  "암속성 강화": "암속성 강화",
  "생존": "생존",
  "오브젝트": "오브젝트",
  "회피율": "회피율",
  "모든 속성 강화": "모든 속성 강화",
  "HP 조건": "HP 조건",
  "받는 데미지": "받는 데미지",
  "화상": "화상",
  "MP MAX": "MP MAX",
  "큐브 조각": "큐브 조각",
  "화속성 저항": "화속성 저항",
  "감전": "감전",
  "출혈": "출혈",
  "마법 부여 효과": "마법 부여 효과",
  "수속성 저항": "수속성 저항",
  "스킬 MP 소모량 감소": "스킬 MP 소모량 감소",
  "명속성 저항": "명속성 저항",
  "스킬 MP 소모량 증가": "스킬 MP 소모량 증가",
  "장비 옵션 조작키": "장비 옵션 조작키",
  "광폭화": "광폭화",
  "암속성 저항": "암속성 저항",
  "MP 조건": "MP 조건",
  "중독": "중독",
  "광부": "P2E",
  "슈퍼 아머": "슈퍼 아머",
  "아칸": "아칸",
  "점프": "점프",
  "HP 소모": "HP 소모",
  "과소모": "과소모",
  "레벨 부스트": "레벨 부스트",
  "빙결": "빙결",
  "상태 이상 내성": "상태 이상 내성",
  "스킬 레벨": "스킬 레벨",
  "지속 시간 증가": "지속 시간 증가",
  "카운터": "카운터",
  "콤보": "콤보",
  "기절": "기절",
  "보호막": "보호막",
  "상태 이상": "상태 이상",
  "석화": "석화",
  "소모품": "소모품",
  "평타": "평타",
  "기본기": "기본기",
  "내성 무시": "내성 무시",
  "무색 큐브 조각 소모 스킬": "무색 큐브 조각 소모 스킬",
  "받는 피해 속성 전환": "받는 피해 속성 전환",
  "부활": "부활",
  "수면": "수면",
  "아이템": "아이템",
  "이동 속도 조건": "이동 속도 조건",
  "점프력": "점프력",
  "중독 데미지": "중독 데미지",
  "커맨드": "커맨드",
  "화상 데미지": "화상 데미지",
  "회복": "회복",
  "HP 0": "HP 0",
  "감전 데미지": "감전 데미지",
  "기본기 숙련": "기본기 숙련",
  "대쉬": "대쉬",
  "모든 속성 저항": "모든 속성 저항",
  "무력화": "무력화",
  "무색 큐브 조각 미소모 스킬": "무색 큐브 조각 미소모 스킬",
  "무큐": "무큐",
  "속성 부여": "속성 부여",
  "속성 저항 조건": "속성 저항 조건",
  "자본": "자본",
  "지속 시간 감소": "지속 시간 감소",
  "출혈 데미지": "출혈 데미지",
  "퀵슬롯": "퀵슬롯",
  "걷기": "걷기",
  "근접": "근접",
  "무적": "무적",
  "백스탭": "백스탭",
  "백어택": "백어택",
  "비 카운터": "비 카운터",
  "비행": "비행",
  "순간이동": "순간이동",
  "스킬 범위": "스킬 범위",
  "아이템 습득": "아이템 습득",
  "암흑": "암흑",
  "저주": "저주",
  "채팅": "채팅",
  "퀵 스탠딩": "퀵 스탠딩",
  "파티원": "파티원",
  "피해증가": "피해증가",
  "MP 소모": "MP 소모",
  "가드": "가드",
  "거대화": "거대화",
  "거북이": "거북이",
  "골드": "골드",
  "대시 공격": "대시 공격",
  "도약": "도약",
  "맞딜": "맞딜",
  "무게": "무게",
  "방어력 무시": "방어력 무시",
  "비각성": "비각성",
  "소울": "소울",
  "소형화": "소형화",
  "스택": "스택",
  "아바타": "아바타",
  "약점 속성": "약점 속성",
  "자세 회복": "자세 회복",
  "적 HP 감소": "적 HP 감소",
  "적중률 조건": "적중률 조건",
  "점프 공격": "점프 공격",
  "질주": "질주",
  "충격파": "충격파",
  "카모플라쥬": "카모플라쥬",
  "크리쳐": "크리쳐",
  "피해 공유": "피해 공유"
}